apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-maven-settings
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings>
        <pluginGroups>
            <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
        </pluginGroups>
        <profiles>
            <profile>
                <id>sonar</id>
                <activation>
                    <activeByDefault>true</activeByDefault>
                </activation>
                <properties>
                    <!-- Optional URL to server. Default value is http://www.bitslovers.com:9000 -->
                    <sonar.host.url>
                      https://sonarqube.contour.e2e.corby.cc
                    </sonar.host.url>
                    <sonar.login>
                      sqp_6919a29a25ee379d03e1d6e8971d9f391ac2428a
                    </sonar.login>
                    <sonar.projectKey>
                      sysco
                    </sonar.projectKey>
                </properties>
            </profile>
         </profiles>
    </settings>
