apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-sonar-pipeline
  namespace: default
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/cpage-pivotal/spring-sensors
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - fetch-repository
      params:
        - name: CONTEXT_DIR
          value: "."
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - verify
            - sonar:sonar
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace